"""Add additional user information fields

Revision ID: 208861e50511
Revises: 
Create Date: 2024-05-16 13:56:26.458476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208861e50511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
