"""Add address field to user

Revision ID: 29046462d8c0
Revises: 208861e50511
Create Date: 2024-05-16 14:01:32.409881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29046462d8c0'
down_revision = '208861e50511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
